blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/YOUR_USERNAME/fundraisely/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/YOUR_USERNAME/fundraisely#readme
    about: Read the documentation for setup and usage guides
